### PR TITLE
Allow angular-toggle-switch.js to be minified by any minifier

### PR DESCRIPTION
**Pull request by tbrushwyler**
This will allow you to safely minify angular-toggle-switch.js without ngmin

### CODE REVIEW

**Comment by bbinet** [comment]
+1
@JumpLink any chance you merge this one?

**Comment by bbinet** [comment]
Thanks @JumpLink !
Would you mind also making a new release with this change, so that bower can pull it?

**Comment by JumpLink** [comment]
done, does it work?

**Comment by bbinet** [comment]
Yes it works perfectly, thanks again.

**Comment by JumpLink** [comment]
Thanks for contributing

**Pull request merged**
